src/Entity/Offer.php
<?php

namespace App\Entity;

use App\Helper\Math;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass="App\Repository\OfferRepository")
 */
class Offer
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\OfferType", fetch="EAGER")
     * @ORM\JoinColumn(nullable=false)
     * @Groups({"shop"})
     */
    private $type;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     * @Groups({"shop"})
     */
    private $commission;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\CommissionType", fetch="EAGER")
     * @ORM\JoinColumn(nullable=false)
     * @Groups({"shop"})
     */
    private $commissionType;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?OfferType
    {
        return $this->type;
    }

    public function setType(? OfferType $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getCommission()
    {
        return $this->commission;
    }

    public function setCommission($commission): self
    {
        $this->commission = $commission;

        return $this;
    }

    public function getCommissionType(): ?CommissionType
    {
        return $this->commissionType;
    }

    public function setCommissionType(? CommissionType $commissionType): self
    {
        $this->commissionType = $commissionType;

        return $this;
    }

    public function isCommissionFiexed()
    {
        return $this->getCommissionType()->getName() == CommissionType::FIXED;
    }

    /**
     * @param $value
     * @return string
     */
    public function calculateCommissionValue($price, $amount)
    {
        if ($this->isCommissionFiexed()) {
            return Math::mul($this->getCommission(), $amount);
        } else {
            return Math::div(Math::mul($this->getCommission(), Math::mul($price, $amount)), '100');
        }
    }

    public function getShortLabel()
    {
        $commissionValue = (string)$this->getCommission();
        $commissionValue = str_replace('.00', '', $commissionValue);
        if ($this->isPercentage()) {
            return $commissionValue . '%';
        } else {
            return '€' . $commissionValue;
        }
    }

    public function isPercentage()
    {
        if ($commissionType = $this->getCommissionType()) {
            return $commissionType->getName() == CommissionType::PERCENT;
        }

        return false;
    }
}

src/Form/Referrer/AffiliateShortLinkType.php
<?php


namespace App\Form\Referrer;


use App\Entity\CardSet\CardSet;
use App\Entity\CardSet\CardSetCard;
use App\Entity\ReferrerLink;
use App\Entity\ShortLinks\AffiliateShortLink;
use App\Entity\ShortLinks\CustomShortLink;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotNull;

class AffiliateShortLinkType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('referrer', EntityType::class, [
                'class' => User::class,
                'choice_label' => 'id',
                'constraints' => [
                    new NotNull(),
                ]
            ])
            ->add('short', TextType::class, [
                'constraints' => [
                    new NotNull(),
                    new Length(['min' => 4, 'max' => 255])
                ]
            ])
            ->add('description', TextType::class, [
                'constraints' => [
                    new Length(['min' => 0])
                ]
            ])
            ->add('facebook_pixel', ChoiceType::class, [
                'choices' => [
                    'Yes' => true,
                    'No' => false
                ]
            ])
            ->add('twitter_pixel', ChoiceType::class, [
                'choices' => [
                    'Yes' => true,
                    'No' => false
                ]
            ])
            ->add('pinterest_pixel', ChoiceType::class, [
                'choices' => [
                    'Yes' => true,
                    'No' => false
                ]
            ])
            ->add('linkedin_pixel', ChoiceType::class, [
                'choices' => [
                    'Yes' => true,
                    'No' => false
                ]
            ])
            ->add('google_pixel', ChoiceType::class, [
                'choices' => [
                    'Yes' => true,
                    'No' => false
                ]
            ])
            ->add('quora_pixel', ChoiceType::class, [
                'choices' => [
                    'Yes' => true,
                    'No' => false
                ]
            ])
            ->add('meta_title', TextType::class, [
                'constraints' => [
                    new NotNull(),
                    new Length(['min' => 4, 'max' => 65535])
                ]
            ])
            ->add('meta_desc', TextType::class, [
                'constraints' => [
                    new Length(['min' => 4, 'max' => 65535])
                ]
            ])
            ->add('meta_image', TextType::class, [
                'constraints' => [
                    new Length(['min' => 4, 'max' => 65535])
                ]
            ])
            ->add('meta_iframe', TextType::class, [
                'constraints' => [
                    new Length(['min' => 4, 'max' => 65535])
                ]
            ]);
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => AffiliateShortLink::class,
            'csrf_protection' => false
        ]);
    }
}

src/Form/Referrer/CardSetCardBackgroundType.php
<?php


namespace App\Form\Referrer;


use App\Entity\CardSet\CardSet;
use App\Entity\CardSet\CardSetCard;
use App\Entity\CardSet\CardSetCardBackground;
use App\Entity\ReferrerLink;
use App\Form\Type\MediaType;
use PhpParser\Node\Expr\BinaryOp\GreaterOrEqual;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Validator\Constraints\GreaterThan;
use Symfony\Component\Validator\Constraints\GreaterThanOrEqual;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\LessThanOrEqual;
use Symfony\Component\Validator\Constraints\NotNull;

class CardSetCardBackgroundType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('width', IntegerType::class, [
                'constraints' => [
                    new NotNull(),
                    new GreaterThan(0),
                    new LessThanOrEqual(1500),
                ]
            ])
            ->add('positionLeft', IntegerType::class, [
                'constraints' => [
                    new NotNull(),
                    new GreaterThanOrEqual(-1500),
                    new LessThanOrEqual(1500),
                ]
            ])
            ->add('positionTop', IntegerType::class, [
                'constraints' => [
                    new NotNull(),
                    new GreaterThanOrEqual(-1500),
                    new LessThanOrEqual(1500),
                ]
            ])
            ->add('media', MediaType::class, [
                'required' => false
            ])
            ->add('url');


    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => CardSetCardBackground::class,
            // @todo: fix it
            'csrf_protection' => false,
        ]);
    }
}

src/Form/Referrer/CardSetCardType.php
<?php


namespace App\Form\Referrer;


use App\Entity\CardSet\CardSet;
use App\Entity\CardSet\CardSetCard;
use App\Entity\ReferrerLink;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotNull;

class CardSetCardType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', null, [
                'constraints' => [
                    new NotNull(),
                    new Length(['min' => 2, 'max' => 128])
                ]
            ])
            ->add('description', null, [
                'constraints' => [
                    new NotNull(),
                    new Length(['min' => 2, 'max' => 10000])
                ]
            ])
            // @todo: restrict below only to current referrer reflink
            ->add('referrerLink', EntityType::class, [
                'class' => ReferrerLink::class,
                'choice_label' => 'id',
                'constraints' => [
                    new NotNull(),
                ]
            ])
            ->add('background', CardSetCardBackgroundType::class, [
                'constraints' => [
                    new NotNull(),
                ]
            ])
            ->add('articleUrl', UrlType::class, [
                'constraints' => [
                    new NotNull(),
                ]
            ])
            ->add('articleUrlName', TextType::class, [
                'constraints' => [
                    new NotNull(),
                ]
            ]);
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => CardSetCard::class,
            // @todo: fix it
            'csrf_protection' => false,
        ]);
    }
}

src/Form/Referrer/IncomeType.php
<?php


namespace App\Form\Referrer;


use App\Entity\EventEntry;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\NotBlank;

class IncomeType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('startDate', DateTimeType::class, [
                'mapped' => false,
                'constraints' => [
                    new NotBlank(),
                ],
            ])
            ->add('endDate', DateTimeType::class, [
                'mapped' => false,
                'constraints' => [
                    new NotBlank(),
                ],
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'csrf_protection' => false,
        ));
    }
}

src/Controller/Account/Referrer/CustomDomainController.php
<?php


namespace App\Controller\Account\Referrer;


use App\Entity\CustomDomain;
use App\Entity\User;
use App\Form\CustomDomainType;
use App\Repository\CustomDomainRepository;
use App\Service\Referrer\CustomDomainService;
use App\Traits\Controller\FormResponseArray;
use Doctrine\ORM\EntityManagerInterface;
use FOS\RestBundle\Exception\InvalidParameterException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Config\Definition\Exception\ForbiddenOverwriteException;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\HttpKernel\Exception\UnprocessableEntityHttpException;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\Serializer\Serializer;

/**
 * Class ReferrerShopLinkController
 * @package App\Controller\Account\Referrer
 * @Security("has_role('ROLE_REFERRER') && is_granted('FULL_PROFILE')")
 */
class CustomDomainController extends AbstractController
{
    use FormResponseArray;

    /** @var CustomDomainRepository */
    private $customDomainRepository;

    /** @var CustomDomainService */
    private $customDomainService;

    /**
     * ReferrerShopController constructor.
     *
     * @param CustomDomainRepository $customDomainRepository
     * @param CustomDomainService $customDomainService
     */
    public function __construct(
        CustomDomainRepository $customDomainRepository,
        CustomDomainService $customDomainService
    )
    {
        $this->customDomainRepository = $customDomainRepository;
        $this->customDomainService = $customDomainService;
    }

    /**
     * @Route("/account/custom-domains", name="account_custom_domains_save", methods={"POST"})
     * @param Request $request
     * @return JsonResponse
     * @throws \Exception
     */
    public function save(Request $request)
    {
        try {
            $customDomain = null;
            $user = $this->getUser();
            $data = $request->request->all();
            unset($data['id']);

            if ($request->request->get('id')) {
                $customDomain = $this->customDomainRepository->find($request->request->get('id'));
            }

            if (!$customDomain) {
                $customDomain = new CustomDomain();
                $customDomain->setUser($user);
            } else if($user->getId() !== $customDomain->getUser()->getId()) {
                throw new \Exception('You don\'t have permission to edit this custom domain', Response::HTTP_UNPROCESSABLE_ENTITY);
            }

            $form = $this->createForm(CustomDomainType::class, $customDomain);
            $form->submit($data);

            if ($form->isSubmitted() && $form->isValid()) {
                /** @var CustomDomain $existsDomain */
                $existsDomain = $this->customDomainRepository->findOneBy([
                    'name' => $data['name']
                ]);

                if ($existsDomain && (
                    ($existsDomain->getId() !== $customDomain->getId()) ||
                    ($existsDomain->getUser()->getId() !== $customDomain->getUser()->getId())
                )) {
                    throw new \Exception('This domain name is already used.', Response::HTTP_UNPROCESSABLE_ENTITY);
                }
                unset($existsDomain);

                $this->customDomainService->save($form->getData());

                $customDomains = $user->getCustomDomains()->map(function (CustomDomain $item) {
                    return [
                        'id' => $item->getId(),
                        'name' => $item->getName()
                    ];
                });

                return new JsonResponse([
                    'message' => 'Custom domain has been saved successfully.',
                    'customDomains' => (array) $customDomains->toArray()
                ], Response::HTTP_OK);
            }

            return new JsonResponse($form->getErrors()[0]->getMessage(), Response::HTTP_UNPROCESSABLE_ENTITY);
        } catch (\Exception $e) {
            return new JsonResponse([$e->getMessage()], ($e->getCode()) ? $e->getCode() : 500);
        }
    }

    /**
     * @Route("/account/custom-domains/{customDomain}/delete", name="account_custom_domains_delete", methods={"POST"})
     * @param CustomDomain $customDomain
     * @return JsonResponse
     */
    public function delete(CustomDomain $customDomain)
    {
        try {
            $user = $this->getUser();

            if (!$customDomain) {
                throw new NotFoundHttpException('Custom domain not found.');
            } else if ($customDomain->getUser()->getId() !== $user->getId()) {
                throw new NotFoundHttpException('Custom domain not found.');
            }

            $this->customDomainService->remove($user, $customDomain);

            $customDomains = $user->getCustomDomains()->map(function (CustomDomain $item) {
                return [
                    'id' => $item->getId(),
                    'name' => $item->getName()
                ];
            });

            return new JsonResponse([
                'message' => 'Custom domain has been removed successfully.',
                'customDomains' => (array) $customDomains->toArray()
            ], Response::HTTP_OK);
        } catch (\Exception $e) {
            return new JsonResponse([$e->getMessage()], Response::HTTP_INTERNAL_SERVER_ERROR);
        }
    }
}

templates/layouts/partials/referrer/links.html.twig
<div class="row companylinks">
    <div class="col-md-3">
        <ul class="nav nav-pills nav-stacked" style="display: flex;flex-direction: column;text-align: left">
            <li class="active"><a data-toggle="pill" href="#home">Basic Apple Reward</a></li>
            <li><a data-toggle="pill" href="#menu1">Specific Apple Reward</a></li>
        </ul>
    </div>
    <div class="col-md-9 col-xs-12">
        <div class="tab-content" style="overflow: hidden;">
            <div id="home" class="tab-pane fade in active">
                <div>
                    <div class="table-responsive">
                        <table class="table table-striped  table-rewards" style="table-layout:fixed;">
                            <thead>
                            <tr>
                                <th rowspan="2" scope="colgroup">Reward<br/>Name</th>
                                <th rowspan="2" scope="colgroup" style="width:150px">Reward<br/>Description</th>
                                <th rowspan="2" scope="colgroup" style="width: 400px;">Reward<br/>URL</th>
                                <th colspan="2" scope="colgroup" style="border-bottom: 0;padding-bottom:0">Reward<br/>CPS</th>
                                <th colspan="2" scope="colgroup" style="border-bottom: 0;padding-bottom:0">Reward<br/>CPL</th>
                            </tr>
                            <tr>
                                <th colspan="1" scope="col" style="padding-top: 0; border-top: 0;">€</th>
                                <th colspan="1" scope="col" style="padding-top: 0; border-top: 0;">%</th>
                                <th colspan="1" scope="col" style="padding-top: 0; border-top: 0;">€</th>
                                <th colspan="1" scope="col" style="padding-top: 0; border-top: 0;">%</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for reward in rewards.basic %}
                                <tr>
                                    <td>
                                        <span class="mobile_table_header">Reward Name: </span>{{ reward.name }}
                                    </td>
                                    <td>
                                        <span class="mobile_table_header">Reward Description: </span>{{ reward.description }}
                                    </td>
                                    <td width="30%" class="rewardlink">
                                        <span class="mobile_table_header">Reward Url: </span><span>{{ reward.url }}</span>
                                        <div class="btn btn-primary btn-xs" data-clipboard-text="{{ reward.url }}">Copy</div>
                                    </td>
                                    <td>
                                        <span class="mobile_table_header">Reward CPS: </span>{% if reward.cps.money > 0 %}
                                        {{ reward.cps.money }}
                                    {% else %}
                                        <i class="fa fa-times-circle"></i>
                                        {% endif %}
                                    </td>
                                    <td>
                                        <span class="mobile_table_header">Reward CPS: </span>{% if reward.cps.percentage > 0 %}
                                        {{ reward.cps.percentage }}
                                    {% else %}
                                        <i class="fa fa-times-circle"></i>
                                        {% endif %}
                                    </td>
                                    <td>
                                        <span class="mobile_table_header">Reward CPL: </span>{% if reward.cpl.money > 0 %}
                                        {{ reward.cpl.money }}
                                    {% else %}
                                        <i class="fa fa-times-circle"></i>
                                        {% endif %}
                                    </td>
                                    <td>
                                        <span class="mobile_table_header">Reward CPL: </span>{% if reward.cpl.percentage > 0 %}
                                        {{ reward.cpl.percentage }}
                                    {% else %}
                                        <i class="fa fa-times-circle"></i>
                                        {% endif %}
                                    </td>
                                </tr>

                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div class="companylink__entry" style="border-top: 0">
                        <h3>Your Personal Store</h3>
                        <h4>www.ValueLink.com/JohnDoe</h4>
                        <div class="btn btn-primary newLinkBtn">Generate Link to Share</div>
                    </div>
                    <div class="linkgenerator-cont">
                        <div id="linkgenerator" class="linkgenerator">
                            <div class="form-group">
                                <label>Shareable link</label>
                                <div class="input-group is-long">
                                    <span class="input-group-addon">ValueLink.com/Apple/JohnDoe</span>
                                    <input type="text" name="Name" class="form-control sharelink"
                                           placeholder="Super-iPhone-6" value="">
                                </div>
                                <span style="    margin-left: auto;
    text-align: right;
    margin-top: 5px;">Create your own link pattern</span>
                            </div>
                            <div class="form-group flex noborder">
                                <label>Destination URL</label>
                                <input type="text" name="Name" class="form-control destlink" placeholder="Reward URL"
                                       value="">
                                <span>Copy & Paste Reward URL</span>
                            </div>
                            <div class="linkgenerator__buttons">
                                <div>
                                    <div class="btn btn-success">Save</div>
                                    <div class="btn btn-danger">Delete</div>
                                </div>
                                <div>
                                    <div class="btn btn-outline-primary">Add to My Store</div>
                                    <div class="btn btn-danger">Delete from My Store</div>
                                </div>
                                <div class="linkgenerator__social">
                                    <div><i style="color: #1778f2; cursor: pointer" class="fa fa-facebook-square"
                                            aria-hidden="true"></i></div>
                                    <div><i style="color: #1da1f2; cursor: pointer" class="fa fa-twitter-square" aria-hidden="true"></i></div>
                                    <div><i style="color: #3b5998; cursor: pointer" class="fa fa-linkedin-square"
                                            aria-hidden="true"></i></div>
                                    <div><i style="color: #25D366; cursor: pointer" class="fa fa-whatsapp" aria-hidden="true"></i></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div id="menu1" class="tab-pane fade">
                <div class="col-md-12" style="background: white">
                    <table class="table table-striped table-rewards">
                        <thead>
                        <tr>
                            <th rowspan="2" scope="colgroup">Reward Name</th>
                            <th rowspan="2" scope="colgroup">Reward Description</th>
                            <th rowspan="2" scope="colgroup" style="width: 200px;">Reward URL</th>
                            <th colspan="2" scope="colgroup" style="border-bottom: 0;padding-bottom:0">Reward
                                CPS</th>
                        </tr>
                        <tr>
                            <th colspan="1" scope="col" style="padding-top: 0; border-top: 0;">€</th>
                            <th colspan="1" scope="col" style="padding-top: 0; border-top: 0;">%</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for reward in rewards.specific %}
                            <tr>
                                <td>
                                    {{ reward.name }}
                                </td>
                                <td>
                                    {{ reward.description }}
                                </td>
                                <td width="30%" class="rewardlink">
                                    <span>{{ reward.url }}</span>
                                    <div class="btn btn-primary btn-xs" data-clipboard-text="{{ reward.url }}">Copy</div>
                                </td>
                                <td>
                                    {% if reward.money > 0 %}
                                        {{ reward.money }}
                                    {% else %}
                                        <i class="fa fa-times-circle"></i>
                                    {% endif %}
                                </td>
                                <td>
                                    {% if reward.percentage > 0 %}
                                        {{ reward.percentage }}
                                    {% else %}
                                        <i class="fa fa-times-circle"></i>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <div class="companylink__entry">
                        <h3>Your Personal Store</h3>
                        <h4>www.ValueLink.com/JohnDoe</h4>
                        <div class="btn btn-primary newLinkBtn">Generate Link to Share</div>
                    </div>
                    <div class="linkgenerator-cont">
                        <div id="linkgenerator" class="linkgenerator">
                            <div class="form-group">
                                <label>Shareable link</label>
                                <div class="input-group is-long">
                                    <span class="input-group-addon">ValueLink.com/Apple/JohnDoe</span>
                                    <input type="text" name="Name" class="form-control sharelink"
                                           placeholder="Super-iPhone-6" value="">
                                </div>
                                <span style="    margin-left: auto;
    text-align: right;
    margin-top: 5px;">Create your own link pattern</span>
                            </div>
                            <div class="form-group flex noborder">
                                <label>Destination URL</label>
                                <input type="text" name="Name" class="form-control destlink" placeholder="Reward URL"
                                       value="">
                                <span>Copy & Paste Reward URL</span>
                            </div>
                            <div class="linkgenerator__buttons">
                                <div>
                                    <div class="btn btn-success">Save</div>
                                    <div class="btn btn-danger">Delete</div>
                                </div>
                                <div>
                                    <div class="btn btn-outline-primary">Add to My Store</div>
                                    <div class="btn btn-danger">Delete from My Store</div>
                                </div>
                                <div class="linkgenerator__social">
                                    <div><i style="color: #1778f2; cursor: pointer" class="fa fa-facebook-square"
                                            aria-hidden="true"></i></div>
                                    <div><i style="color: #1da1f2; cursor: pointer" class="fa fa-twitter-square" aria-hidden="true"></i></div>
                                    <div><i style="color: #3b5998; cursor: pointer" class="fa fa-linkedin-square"
                                            aria-hidden="true"></i></div>
                                    <div><i style="color: #25D366; cursor: pointer" class="fa fa-whatsapp" aria-hidden="true"></i></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/clipboard@2/dist/clipboard.min.js"></script>

<script>
    (function () {
        new ClipboardJS('.rewardlink .btn');

        const linkGenerator = $("#linkgenerator").clone().prop('outerHTML');

        $(".newLinkBtn").each(function () {
            $(this).click(function () {
                $(this).parent().parent().find(".linkgenerator-cont").prepend(linkGenerator);
            });
        });

    })();
</script>